My Dev Org/src/objects/Call__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Calls</relationshipLabel>
        <relationshipName>Calls</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Calls</relationshipLabel>
        <relationshipName>Calls</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Call</label>
    <nameField>
        <label>Call Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Calls</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

My Dev Org/src/classes/wrapper1.cls
public class wrapper1{

     public Account myA {get;set;}
     public Call__c myB {get;set;}
     public Contact myC {get;set;}

     public wrapper1(){
          myA = new Account();
          myB = new Call__c();
          myC = new Contact();
     }

     public void saveObjects(){
          insert myA;
          myC.AccountId= myA.Id;
          insert myC;
          myB.Account__c= myA.Id;
          myB.Contact__c=myC.id;          
          insert myB;          
     }
}